# Generated by Django 4.2 on 2023-04-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('idtest', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de test')),
            ],
        ),
    ]
